version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: banco-dados
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: meu_banco
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  app1:
    build: ./app
    container_name: app1
    restart: always
    environment:
      - SERVER_NAME=container-1
    depends_on:
      - db
    networks:
      - app_network

  app2:
    build: ./app
    container_name: app2
    restart: always
    environment:
      - SERVER_NAME=container-2
    depends_on:
      - db
    networks:
      - app_network

  app3:
    build: ./app
    container_name: app3
    restart: always
    environment:
      - SERVER_NAME=container-3
    depends_on:
      - db
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: loadbalancer
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
