version: '3.8'

services:
  db:
    image: postgres:latest  # Usa a última versão do PostgreSQL
    container_name: banco-dados
    restart: always
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    ports:
      - "5432:5432"  # Mapeia a porta do banco de dados
    volumes:
      - db_data:/var/lib/postgresql/data  # Persistência de dados

  app1:
    image: minha-aplicacao:latest
    container_name: app1
    restart: always
    depends_on:
      - db  # Aguarda o banco de dados estar disponível antes de iniciar
    networks:
      - app_network

  app2:
    image: minha-aplicacao:latest
    container_name: app2
    restart: always
    depends_on:
      - db
    networks:
      - app_network

  app3:
    image: minha-aplicacao:latest
    container_name: app3
    restart: always
    depends_on:
      - db
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: loadbalancer
    restart: always
    depends_on:
      - app1
      - app2
      - app3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Carrega a configuração do Nginx
    networks:
      - app_network

networks:
  app_network:

volumes:
  db_data: